volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: heiikousen/foodgram_backend
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/media/

  frontend:
    env_file: .env
    image: heiikousen/foodgram_frontend
    command: cp -r /frontend/build/. /static/
    volumes:
      - static:/static
  
  gateway:
    image: heiikousen/foodgram_gateway
    ports:
      - 9000:80
    depends_on:
      - backend
    volumes:
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/staticfiles/
      - media:/media/