volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: foodgram-db
    image: postgres:13
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram-backend
    image: heiikousen/foodgram_backend
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./static:/backend_static
      - ./media:/media/

  frontend:
    env_file: .env
    image: heiikousen/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/app/frontend_static
  
  gateway:
    container_name: foodgram-proxy
    image: heiikousen/foodgram_gateway
    ports:
      - 9000:80
    depends_on:
      - backend
    volumes:
      - ./docs/:/usr/share/nginx/html/api/docs/
      - ./static:/staticfiles/
      - ./media:/media/