[tool.ruff]
line-length = 79

[tool.ruff.per-file-ignores]
"migrations/*.py" = ["ALL"]
select = ["I"]

[[tool.ruff.isort]]
known_first_party = ["foodgram"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
force_sort_within_sections = true
lines_after_imports = 2