# Generated by Django 3.2.16 on 2024-09-09 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20240909_1703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
