# Generated by Django 3.2.16 on 2024-09-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_delete_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='text',
            field=models.TextField(default='Описание отсутствует', verbose_name='Тект'),
        ),
    ]
