# Generated by Django 3.2.16 on 2024-09-16 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0006_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'default_related_name': 'ingredients', 'verbose_name': 'Ингридиент', 'verbose_name_plural': 'Ингридиенты'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'default_related_name': 'recipes', 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'default_related_name': 'tags', 'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='recipe',
            new_name='recipes',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='user',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='unit',
            new_name='measurement_unit',
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='ingredient',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='recipe',
            new_name='recipes',
        ),
        migrations.RenameField(
            model_name='shoppinglist',
            old_name='recipe',
            new_name='recipes',
        ),
        migrations.RenameField(
            model_name='shoppinglist',
            old_name='user',
            new_name='users',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipes.RecipeIngredient', to='recipes.Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', to='recipes.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('users', 'recipes')},
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('recipes', 'ingredients', 'amount')},
        ),
        migrations.AlterUniqueTogether(
            name='shoppinglist',
            unique_together={('users', 'recipes')},
        ),
    ]
