# Generated by Django 3.2.16 on 2024-09-23 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_subscribe_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'ordering': ('author',), 'verbose_name': 'Подписчик', 'verbose_name_plural': 'Подписчики'},
        ),
    ]
